### ISSUE TITLE
[iOS] AsyncStorage data persists after uninstalling and re-installing app

### ISSUE THREAD

**Issue by bachhuberdesign** [react-native-async-storage/async-storage#342] opened 2020-04-23 22:57 UTC
## Current behavior
Using the latest stable release (1.9.0), AsyncStorage items that are set persist after an iOS app is uninstalled and then re-installed.

## Expected behavior
AsyncStorage should be completely clear after uninstalling/reinstalling an app. This is how the framework bundled AsyncStorage behaves, so one would expect the community version to function the same way. If this persistence is intentional, it should be documented (as far as I can tell there is nothing in the docs that would explain this behavior, but I might have missed something). Apologies if I am mistaken or if this issue has been reported already.

## Repro steps
1. `AsyncStorage.setItem('someKey', 'someData');`
2. Uninstall iOS app
3. Re-install iOS app
4. `const data = AsyncStorage.getItem('someKey'); // returns someData`

## Environment

- **Async Storage version**: 1.9.0
- **React-Native version**: 0.62.2
- **Platform tested**: iOS 13.3

**Comment by Krizzu** [comment] 2020-04-24 07:57
Interesting. I did just a quick check (init new app, add AsyncStorage, save data, removed app, installed again, read data) and the data is indeed removed.
Are you using real device or simulator?

**Comment by madman61rus** [comment] 2020-05-08 08:31
I have the same problem on IOS simulator

**Comment by bachhuberdesign** [comment] 2020-05-08 14:05
My issue was on simulator as well.

**Comment by kennyho-ml** [comment] 2020-06-16 19:12
I have this problem using expo 37 + react native 61.4.

**Comment by Krizzu** [comment] 2020-06-17 17:43
Can anyone provide a project where issue is reproducible ?

**Comment by JacquesLeupin** [comment] 2020-07-10 22:05
I've run into this as well on a physical iOS device, using:

```
"@react-native-community/async-storage": "^1.11.0",
"react-native": "0.62.2",
```

Project repo is private, but I can provide more details upon request.  App name is Serenity: Guided Mental Health.

**Comment by Krizzu** [comment] 2020-07-11 11:33
@JacquesLeupin Please do include some repro steps, thanks!

**Comment by developius** [comment] 2020-08-16 06:03
How can we maintain this behaviour? I have a scenario where it's imperative that the data in AsyncStorage can be persisted across uninstalls/reinstalls. This is because a unique device ID is stored within it.
I read that iCloud will backup the data and can recover it when reinstalled, and the same for Android with the Play Store. Is that true?

**Comment by exotexot** [comment] 2020-08-19 22:13
@developius maybe storing your device id in keychain solve your problem.

I also think that clearing data after app uninstall is important to avoid accumulation of garbage...

**Comment by nishanttatva** [comment] 2020-08-25 10:40
@JacquesLeupin were you able to fix this?

**Comment by JacquesLeupin** [comment] 2020-08-25 19:30
@nishanttatva nope, i never found a fix for this issue.

our app uses firebase for auth, and we refactored to avoid storing most data in `AsyncStorage`.  to automatically log out a user, we implemented this [workaround](https://github.com/invertase/react-native-firebase/issues/694).

**Comment by developius** [comment] 2020-08-25 20:59
@exotexot good call, thanks!

**Comment by Krizzu** [comment] 2020-08-28 11:57
Since we're storing data in `Application Support` directory, it's **backed up** [by default](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html).

We need a way to opt out from doing that. Going to work on that in upcoming days

**Comment by nishanttatva** [comment] 2020-09-14 04:02
@Krizzu 

> We need a way to opt out from doing that. Going to work on that in upcoming days

Were you able to find anything?

**Comment by fbartho** [comment] 2020-10-07 17:44
We also need this fix as it causes problems when users try to uninstall/reinstall (particularly noticeable when trying to experience a First-App-Launch experience)! This is a pretty urgent issue for our Application, so I'd love to help.

There's a filesystem flag that can be set on files to enable/disable this type of behavior on iOS.

@Krizzu do you need any help getting a solution for this?

From an API perspective @Krizzu, what did you want for this? Solutions that come to mind:
A. a standalone global flag that users could attach to RN.AsyncStorage -- `RN.AsyncStorage.setBackupMode("no-restore")`
- users could setItem with a magic key: `__ASYNC_STORAGE_BACKUP_MODE__ = "no-restore"`
- Change this from a Singleton-type API where there's only 1 Storage "Domain" to multiple storage domains + add an API to configure behavior for each domain. -- This would be multiple files on disk, and users would need an API to get "other" storage domains. -- This would be the biggest API enhancement, but it could be backwards compatible…

**Comment by Krizzu** [comment] 2020-10-08 21:09
@fbartho 

I've created an initial PR that has backup feature toggling. I cannot repro this myself, so it'd be great if you (or anyone else) could give it a try.

Regarding using that feature - I thought about adding an entry to `package.json` like `AsyncStorage` where we'd keep all the feature flags (for Android too). We'd have to find a way to read it on AppLaunch (where AsyncStorage init is happening).

**Comment by fbartho** [comment] 2020-10-14 23:37
@Krizzu we'd be happy to try a beta build that has the final implementation of your proposed feature -- I've commented on your PR for now with some further thoughts. This is affecting our app in production, so we're comfortable testing an appropriate beta build in our normal QA process.

**Comment by hannahcx** [comment] 2020-10-16 11:46
Hello what is the status of this? It is interesting one IOS app is storing values correctly, and store is not persisted on reinstall. Another app the values are persisted on reinstall, so I'm wondering is it due to the fact "On iOS, AsyncStorage is backed by native code that stores small values in a serialized dictionary and larger values in separate files." That maybe this second app has larger values and is getting stored in a different place in the system? We are running into issues with  this so I'm wondering the status.

**Closed** 2020-10-21 17:03 UTC
Labels: enhancement, platform: iOS, platform: macOS

**Comment by johnjoshuadablo** [comment] 2022-01-17 06:25
Any status on this?

**Comment by topwebtek7** [comment] 2022-02-14 10:12
Any workaround to this issue?

**Comment by falcoagustin** [comment] 2022-03-20 19:19
Also interested about this fix.

**Comment by endronk** [comment] 2022-04-01 01:24
From what I read on @krizzu 's PR [here](https://github.com/react-native-async-storage/async-storage/pull/455#issuecomment-709358442), it should already be excluded from iCloud backup. Also [here](https://react-native-async-storage.github.io/async-storage/docs/advanced/backup/).
I also cannot check myself, but some of our users still experience this data persistence.

**Comment by endronk** [comment] 2022-04-01 02:17
Ahh, my bad. We use [expo-secure-store](https://docs.expo.dev/versions/latest/sdk/securestore/) on some of our data, and they go into backup.
> Please note that for iOS standalone apps, data stored with expo-secure-store can persist across app installs.

**Comment by SophieJung7** [comment] 2023-04-18 03:05
Any update on this PR?

**Comment by feri-irawan** [comment] 2024-06-12 09:10
Same problem, but in Android <= 10, the data still there after uninstall and reinstall the app.
I am using zustand + AsyncStorage for auth session

**Comment by sLurPPPeRsTaR** [comment] 2025-03-11 14:55
![Image](https://github.com/user-attachments/assets/e77f08e0-c15e-4547-8919-485e58ec5e92)

**Comment by shahana0994** [comment] 2025-12-03 14:45
I have upgraded react native version 0.77.3 and the AppDelegate.mm changed to AppDelegate.swift, so I need to update the code. Below code worked for me.

/**
 Deletes all Keychain items accessible by this app if this is the first time the user launches the app
 */
fileprivate func ClearKeychainIfNecessary() {
    if !UserDefaults.standard.bool(forKey: "HAS_RUN_BEFORE") {

        UserDefaults.standard.set(true, forKey: "HAS_RUN_BEFORE")

        let secItemClasses = [
            kSecClassGenericPassword,
            kSecClassInternetPassword,
            kSecClassCertificate,
            kSecClassKey,
            kSecClassIdentity
        ] as [CFString]

        for secClass in secItemClasses {
            let spec = [kSecClass as String: secClass] as NSDictionary
            SecItemDelete(spec)
        }
    }
}

@main
class AppDelegate: RCTAppDelegate {
  override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
    FirebaseApp.configure()
    ClearKeychainIfNecessary()

//...other code
