### ISSUE TITLE
Not able to generate release app

### ISSUE THREAD

**Issue by AjayShivanagol** [react-native-async-storage/async-storage#718] opened 2021-11-26 14:07 UTC
### What happened?

When I am doing ./gradlew assembleRelease i am getting the following error.
tried following things but had no luck.

 ./gradlew clean
 build -> clean Project,
 build -> Rebuild project,
 Invalidate cache and restart,
 deletated .gradle file from Android folder + ./gradle/cache file from home directry  

> Task :app:minifyReleaseWithR8 FAILED

/home/ajays/.gradle/caches/transforms-2/files-2.1/1908e998bd9a5e1d19271bb8aa2de301/jetified-react-native-async-storage-1.15.5-jitsi-9163301-runtime.jar: R8: Type com.reactnativecommunity.asyncstorage.AsyncStoragePackage is defined multiple times: /home/ajays/.gradle/caches/transforms-2/files-2.1/1908e998bd9a5e1d19271bb8aa2de301/jetified-react-native-async-storage-1.15.5-jitsi-9163301-runtime.jar:com/reactnativecommunity/asyncstorage/AsyncStoragePackage.class, /home/ajays/code/mobile/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/runtime_library_classes_jar/release/classes.jar:com/reactnativecommunity/asyncstorage/AsyncStoragePackage.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /home/ajays/.gradle/caches/transforms-2/files-2.1/1908e998bd9a5e1d19271bb8aa2de301/jetified-react-native-async-storage-1.15.5-jitsi-9163301-runtime.jar:com/reactnativecommunity/asyncstorage/AsyncStoragePackage.class

please help me in resolving Thanks in Advance.

### Version

    "@react-native-async-storage/async-storage": "1.15.5",

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
System:
    OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 168.72 MB / 15.43 GB
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
    Yarn: Not Found
    npm: 8.0.0 - ~/.nvm/versions/node/v16.11.1/bin/npm
    Watchman: 4.9.0 - /usr/bin/watchman
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
    Python: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

On doing  ./gradlew assembleRelease i am facing this

**Comment by tido64** [comment] 2021-11-26 15:03
Can you post the full build log? I cannot repro this locally:
```
% ./gradlew assembleRelease
Configuration on demand is an incubating feature.

> Configure project :
[AsyncStorage] Using Next storage: true

> Configure project :app
WARNING:: The option 'android.useDeprecatedNdk' is deprecated.
The current default is 'false'.
It has been removed from the current version of the Android Gradle plugin.
NdkCompile is no longer supported

> Task :react-native-async-storage_async-storage:kaptReleaseKotlin
/~/android/build/tmp/kapt3/stubs/release/com/reactnativecommunity/asyncstorage/next/StorageDb.java:7: warning: Schema export directory is not provided to the annotation processor so we cannot export the schema. You can either provide `room.schemaLocation` annotation processor argument OR set exportSchema to false.
public abstract class StorageDb extends androidx.room.RoomDatabase {
                ^

> Task :react-native-async-storage_async-storage:compileReleaseKotlin
w: /~/android/src/main/java/com/reactnativecommunity/asyncstorage/next/ArgumentHelpers.kt: (41, 17): Unchecked cast: ArrayList<Any!> to List<String>

> Task :react-native-async-storage_async-storage:compileReleaseJavaWithJavac
Note: /~/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /~/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

BUILD SUCCESSFUL in 43s
96 actionable tasks: 49 executed, 47 up-to-date
```

**Comment by AjayShivanagol** [comment] 2021-11-26 15:34
```
./gradlew assembleRelease

> Configure project :@react-native-community_netinfo
WARNING: The option setting 'android.enableDexingArtifactTransform.desugaring=false' is experimental.
The current default is 'true'.
WARNING: The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

> Configure project :react-native-reanimated
WARNING: The specified Android SDK Build Tools version (28.0.3) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.1.0.
Android SDK Build Tools 29.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
Warning: Mapping new ns http://schemas.android.com/repository/android/common/02 to old ns http://schemas.android.com/repository/android/common/01
Warning: Mapping new ns http://schemas.android.com/repository/android/generic/02 to old ns http://schemas.android.com/repository/android/generic/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/addon2/02 to old ns http://schemas.android.com/sdk/android/repo/addon2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/repository2/02 to old ns http://schemas.android.com/sdk/android/repo/repository2/01
Warning: Mapping new ns http://schemas.android.com/sdk/android/repo/sys-img2/02 to old ns http://schemas.android.com/sdk/android/repo/sys-img2/01

> Task :@react-native-community_netinfo:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
                 Welcome to React Native!
                Learn once, write anywhere


info Writing bundle output to:, /home/ajays/code/mobile/android/app/build/generated/assets/react/release/index.android.dvc.bundle
info Writing sourcemap output to:, /home/ajays/code/mobile/android/app/build/generated/sourcemaps/react/release/index.android.dvc.bundle.map
info Done writing bundle output
info Done writing sourcemap output
info Copying 277 asset files
info Done copying assets

> Task :app:processReleaseMainManifest
[:react-native-gesture-handler] /home/ajays/code/mobile/node_modules/react-native-gesture-handler/android/build/intermediates/library_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.swmansion.gesturehandler.react' used in: :react-native-gesture-handler, com.facebook.react:react-native-gesture-handler:1.10.3-jitsi-9163301.
[:react-native-community_google-signin] /home/ajays/code/mobile/node_modules/@react-native-community/google-signin/android/build/intermediates/library_manifest/release/AndroidManifest.xml Warning:
        Package name 'co.apptailor.googlesignin' used in: :react-native-community_google-signin, com.facebook.react:react-native-google-signin:3.0.1-jitsi-9163301.
[:react-native-screens] /home/ajays/code/mobile/node_modules/react-native-screens/android/build/intermediates/library_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.swmansion.rnscreens' used in: :react-native-screens, com.facebook.react:react-native-screens:2.18.1-jitsi-9163301.
[:react-native-async-storage_async-storage] /home/ajays/code/mobile/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/library_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.reactnativecommunity.asyncstorage' used in: :react-native-async-storage_async-storage, com.facebook.react:react-native-async-storage:1.15.5-jitsi-9163301.
[:react-native-reanimated] /home/ajays/code/mobile/node_modules/react-native-reanimated/android/build/intermediates/library_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.swmansion.reanimated' used in: :react-native-reanimated, com.facebook.react:react-native-reanimated:1.13.3-jitsi-9163301.
[:react-native-community_netinfo] /home/ajays/code/mobile/node_modules/@react-native-community/netinfo/android/build/intermediates/library_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.reactnativecommunity.netinfo' used in: :react-native-community_netinfo, com.facebook.react:react-native-community_netinfo:4.1.5-jitsi-9163301.
[:react-native-safe-area-context] /home/ajays/code/mobile/node_modules/react-native-safe-area-context/android/build/intermediates/library_manifest/release/AndroidManifest.xml Warning:
        Package name 'com.th3rdwave.safeareacontext' used in: :react-native-safe-area-context, com.facebook.react:react-native-safe-area-context:3.3.2-jitsi-9163301.
[:react-native-community_masked-view] /home/ajays/code/mobile/node_modules/@react-native-community/masked-view/android/build/intermediates/library_manifest/release/AndroidManifest.xml Warning:
        Package name 'org.reactnative.maskedview' used in: :react-native-community_masked-view, com.facebook.react:react-native-masked-view_masked-view:0.2.6-jitsi-9163301.

> Task :react-native-async-storage_async-storage:compileReleaseJavaWithJavac
Note: /home/ajays/code/mobile/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStorageModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/ajays/code/mobile/node_modules/@react-native-async-storage/async-storage/android/src/main/java/com/reactnativecommunity/asyncstorage/AsyncStoragePackage.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-community_datetimepicker:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-community_google-signin:compileReleaseJavaWithJavac
Note: /home/ajays/code/mobile/node_modules/@react-native-community/google-signin/android/src/main/java/co/apptailor/googlesignin/RNGoogleSigninModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/ajays/code/mobile/node_modules/@react-native-community/google-signin/android/src/main/java/co/apptailor/googlesignin/RNGoogleSigninModule.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-community_netinfo:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-community_toolbar-android:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-fbsdk:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/ajays/code/mobile/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-fs:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-gesture-handler:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-image-picker:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :react-native-jitsi-meet:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/ajays/code/mobile/node_modules/react-native-jitsi-meet/android/src/main/java/com/reactnativejitsimeet/RNJitsiMeetViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-push-notification:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/ajays/code/mobile/node_modules/react-native-push-notification/android/src/main/java/com/dieam/reactnativepushnotification/modules/RNPushNotification.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-reanimated:compileReleaseJavaWithJavac
Note: /home/ajays/code/mobile/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/ajays/code/mobile/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-screens:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :react-native-safe-area-context:compileReleaseJavaWithJavac
Note: /home/ajays/code/mobile/node_modules/react-native-safe-area-context/android/src/main/java/com/th3rdwave/safeareacontext/SafeAreaUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:minifyReleaseWithR8 FAILED
/home/ajays/.gradle/caches/transforms-2/files-2.1/1908e998bd9a5e1d19271bb8aa2de301/jetified-react-native-async-storage-1.15.5-jitsi-9163301-runtime.jar: R8: Type com.reactnativecommunity.asyncstorage.AsyncStoragePackage is defined multiple times: /home/ajays/.gradle/caches/transforms-2/files-2.1/1908e998bd9a5e1d19271bb8aa2de301/jetified-react-native-async-storage-1.15.5-jitsi-9163301-runtime.jar:com/reactnativecommunity/asyncstorage/AsyncStoragePackage.class, /home/ajays/code/mobile/node_modules/@react-native-async-storage/async-storage/android/build/intermediates/runtime_library_classes_jar/release/classes.jar:com/reactnativecommunity/asyncstorage/AsyncStoragePackage.class

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /home/ajays/.gradle/caches/transforms-2/files-2.1/1908e998bd9a5e1d19271bb8aa2de301/jetified-react-native-async-storage-1.15.5-jitsi-9163301-runtime.jar:com/reactnativecommunity/asyncstorage/AsyncStoragePackage.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 36s
390 actionable tasks: 98 executed, 292 up-to-date
```

**Comment by Krizzu** [comment] 2021-11-26 16:09
It seems like you have a mix of versions of AsyncStorage (one from RN Community, one from this Org):

```
/home/ajays/.gradle/caches/transforms-2/files-2.1/1908e998bd9a5e1d19271bb8aa2de301/jetified-react-native-async-storage-1.15.5-jitsi-9163301-runtime.jar: R8: Type com.reactnativecommunity.asyncstorage.AsyncStoragePackage is defined multiple times: /home/ajays/.gradle/caches/transforms-2/files-2.1/1908e998bd9a5e1d19271bb8aa2de301/jetified-react-native-async-storage-1.15.5-jitsi-9163301-runtime.jar:**com/reactnativecommunity/asyncstorage/AsyncStoragePackage**.class, 

/home/ajays/code/mobile/node_modules/**@react-native-async-storage/async-storage**/android/build/intermediates/runtime_library_classes_jar/release/classes.jar:com/reactnativecommunity/asyncstorage/AsyncStoragePackage.class
```

Check package.json if you don't have the old package there

**Comment by AjayShivanagol** [comment] 2021-11-27 04:31
```
{
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "build:ios": "react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@arelstone/react-native-email-chip": "2.0.1",
    "@react-native-async-storage/async-storage": "1.15.5",
    "@react-native-community/checkbox": "0.5.0",
    "@react-native-community/clipboard": "1.2.3",
    "@react-native-community/datetimepicker": "3.0.8",
    "@react-native-community/google-signin": "4.0.3",
    "@react-native-community/masked-view": "0.1.9",
    "@react-native-community/netinfo": "4.1.5",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-navigation/drawer": "5.9.0",
    "@react-navigation/native": "5.4.0",
    "@react-navigation/stack": "5.2.11",
    "@twotalltotems/react-native-otp-input": "1.3.11",
    "apisauce": "1.1.1",
    "axios": "0.19.2",
    "base-64": "0.1.0",
    "buffer": "5.6.0",
    "hermes-engine": "0.4.0",
    "lodash.clonedeep": "4.5.0",
    "lodash.debounce": "4.0.8",
    "lodash.get": "4.4.2",
    "lodash.groupby": "4.6.0",
    "moment": "2.27.0",
    "moment-timezone": "0.5.31",
    "patch-package": "6.2.2",
    "react": "16.11.0",
    "react-native": "0.62.2",
    "react-native-animatable": "1.3.3",
    "react-native-country-picker-modal": "1.11.0",
    "react-native-dotenv": "2.5.3",
    "react-native-dropdown-picker": "3.7.8",
    "react-native-fbsdk": "2.0.0",
    "react-native-fs": "2.16.6",
    "react-native-gesture-handler": "1.6.1",
    "react-native-image-picker": "2.3.4",
    "react-native-jitsi-meet": "^2.1.2",
    "react-native-modal": "11.5.6",
    "react-native-modal-datetime-picker": "^9.0.0",
    "react-native-paper": "4.0.1",
    "react-native-phone-input": "0.2.4",
    "react-native-push-notification": "7.3.1",
    "react-native-reanimated": "1.8.0",
    "react-native-restart": "0.0.17",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "2.5.0",
    "react-native-simple-dialogs": "1.2.1",
    "react-native-simple-toast": "1.1.2",
    "react-native-vector-icons": "^7.1.0",
    "react-redux": "7.2.0",
    "redux": "4.0.5",
    "redux-persist": "6.0.0",
    "redux-saga": "1.1.3",
    "redux-thunk": "2.3.0",
    "reduxsauce": "1.1.2",
    "unorm": "1.6.0"
  },
  "devDependencies": {
    "@babel/core": "7.10.5",
    "@babel/runtime": "7.10.5",
    "@react-native-community/eslint-config": "2.0.0",
    "babel-jest": "26.1.0",
    "babel-plugin-module-resolver": "4.0.0",
    "eslint": "7.4.0",
    "jest": "26.1.0",
    "metro-react-native-babel-preset": "0.60.0",
    "react-test-renderer": "16.13.1"
  },
  "jest": {
    "preset": "react-native"
  }
}

```
No I don't have

**Comment by tido64** [comment] 2021-12-01 10:25
What version of Gradle are you using? Have you tried tried using the latest 6.x?

**Comment by tigerjiang** [comment] 2021-12-02 09:50
@AjayShivanagol I have the same issue , do you have fix it?

**Comment by slrwinter** [comment] 2022-01-27 03:43
any update? I got same issue

**Comment by krizzu** [comment] 2022-01-27 11:07
Please post gradle errors, cannot help without them.

**Comment by aryantschics** [comment] 2022-01-28 13:52
@krizzu I am using React native 0.67 and latest AsyncStorage,in my case Build is generating for debug and release but Release Build is crashing after splash screen.Errors are below thanx.





01-28 19:13:46.327   390   569 E installd: Couldn't opendir /data/app/vmdl168094817.tmp: No such file or directory
01-28 19:13:46.327   390   569 E installd: Failed to delete /data/app/vmdl168094817.tmp: No such file or directory
01-28 19:13:47.037  1204  1578 E GmsClient: unable to connect to service: com.google.android.gms.auth.key.retrieval.service.START on com.google.android.gms
01-28 19:13:47.481  1204 32698 E ConfigFileUtils: Failed to read config file: /data/user_de/0/com.google.android.gms/app_chimera/next_container.pb: open failed: ENOENT (No such file or directory)
01-28 19:13:49.275 32751 32751 E SoLoader: couldn't find DSO to load: libjscexecutor.so caused by: dlopen failed: library "libjsc.so" not found: needed by /data/app/~~24vb5InF0qeXObBbIQHUoQ==/com.test.naturesbasket-2b9yUKueKzZmfNstMIpNFA==/lib/x86/libjscexecutor.so in namespace classloader-namespace result: 0
01-28 19:13:49.809 32751   352 E SoLoader: couldn't find DSO to load: libhermes-executor-debug.so caused by: dlopen failed: cannot locate symbol "_ZN8facebook6hermes13HermesRuntime11getDebuggerEv" referenced by "/data/app/~~24vb5InF0qeXObBbIQHUoQ==/com.test.naturesbasket-2b9yUKueKzZmfNstMIpNFA==/lib/x86/libhermes-executor-common-debug.so"... result: 0
01-28 19:13:50.760 32751   366 E ReactNativeJS: TypeError: undefined is not a function
01-28 19:13:50.760 32751   366 E ReactNativeJS: 
01-28 19:13:50.760 32751   366 E ReactNativeJS: This error is located at:
01-28 19:13:50.760 32751   366 E ReactNativeJS:     in App
01-28 19:13:50.760 32751   366 E ReactNativeJS:     in RCTView
01-28 19:13:50.760 32751   366 E ReactNativeJS:     in Unknown
01-28 19:13:50.760 32751   366 E ReactNativeJS:     in RCTView
01-28 19:13:50.760 32751   366 E ReactNativeJS:     in Unknown
01-28 19:13:50.760 32751   366 E ReactNativeJS:     in AppContainer, js engine: hermes
01-28 19:13:50.763 32751   366 E ReactNativeJS: TypeError: undefined is not a function
01-28 19:13:50.763 32751   366 E ReactNativeJS: 
01-28 19:13:50.763 32751   366 E ReactNativeJS: This error is located at:
01-28 19:13:50.763 32751   366 E ReactNativeJS:     in App
01-28 19:13:50.763 32751   366 E ReactNativeJS:     in RCTView
01-28 19:13:50.763 32751   366 E ReactNativeJS:     in Unknown
01-28 19:13:50.763 32751   366 E ReactNativeJS:     in RCTView
01-28 19:13:50.763 32751   366 E ReactNativeJS:     in Unknown
01-28 19:13:50.763 32751   366 E ReactNativeJS:     in AppContainer, js engine: hermes
01-28 19:13:50.782 32751   367 E unknown:ReactNative: TypeError: undefined is not a function
01-28 19:13:50.782 32751   367 E unknown:ReactNative: 
01-28 19:13:50.782 32751   367 E unknown:ReactNative: This error is located at:
01-28 19:13:50.782 32751   367 E unknown:ReactNative:     in App
01-28 19:13:50.782 32751   367 E unknown:ReactNative:     in RCTView
01-28 19:13:50.782 32751   367 E unknown:ReactNative:     in Unknown
01-28 19:13:50.782 32751   367 E unknown:ReactNative:     in RCTView
01-28 19:13:50.782 32751   367 E unknown:ReactNative:     in Unknown
01-28 19:13:50.782 32751   367 E unknown:ReactNative:     in AppContainer, js engine: hermes, stack:
01-28 19:13:50.782 32751   367 E unknown:ReactNative: App@1:543776
01-28 19:13:50.782 32751   367 E unknown:ReactNative: renderWithHooks@1:86937
01-28 19:13:50.782 32751   367 E unknown:ReactNative: beginWork$1@1:126236
01-28 19:13:50.782 32751   367 E unknown:ReactNative: performUnitOfWork@1:112492
01-28 19:13:50.782 32751   367 E unknown:ReactNative: workLoopSync@1:112350
01-28 19:13:50.782 32751   367 E unknown:ReactNative: renderRootSync@1:112234
01-28 19:13:50.782 32751   367 E unknown:ReactNative: performSyncWorkOnRoot@1:109609
01-28 19:13:50.782 32751   367 E unknown:ReactNative: flushSyncCallbacks@1:77235
01-28 19:13:50.782 32751   367 E unknown:ReactNative: scheduleUpdateOnFiber@1:107268
01-28 19:13:50.782 32751   367 E unknown:ReactNative: updateContainer@1:117581
01-28 19:13:50.782 32751   367 E unknown:ReactNative: anonymous@1:127243
01-28 19:13:50.782 32751   367 E unknown:ReactNative: renderApplication@1:446634
01-28 19:13:50.782 32751   367 E unknown:ReactNative: run@1:443468
01-28 19:13:50.782 32751   367 E unknown:ReactNative: runApplication@1:444004
01-28 19:13:50.782 32751   367 E unknown:ReactNative: __callFunction@1:53719
01-28 19:13:50.782 32751   367 E unknown:ReactNative: anonymous@1:52206
01-28 19:13:50.782 32751   367 E unknown:ReactNative: __guard@1:53164
01-28 19:13:50.782 32751   367 E unknown:ReactNative: callFunctionReturnFlushedQueue@1:52164
01-28 19:13:50.787 32751   367 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-28 19:13:50.787 32751   367 E AndroidRuntime: Process: com.test.naturesbasket, PID: 32751
01-28 19:13:50.787 32751   367 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: undefined is not a function
01-28 19:13:50.787 32751   367 E AndroidRuntime: 
01-28 19:13:50.787 32751   367 E AndroidRuntime: This error is located at:
01-28 19:13:50.787 32751   367 E AndroidRuntime:     in App
01-28 19:13:50.787 32751   367 E AndroidRuntime:     in RCTView
01-28 19:13:50.787 32751   367 E AndroidRuntime:     in Unknown
01-28 19:13:50.787 32751   367 E AndroidRuntime:     in RCTView
01-28 19:13:50.787 32751   367 E AndroidRuntime:     in Unknown
01-28 19:13:50.787 32751   367 E AndroidRuntime:     in AppContainer, js engine: hermes, stack:
01-28 19:13:50.787 32751   367 E AndroidRuntime: App@1:543776
01-28 19:13:50.787 32751   367 E AndroidRuntime: renderWithHooks@1:86937
01-28 19:13:50.787 32751   367 E AndroidRuntime: beginWork$1@1:126236
01-28 19:13:50.787 32751   367 E AndroidRuntime: performUnitOfWork@1:112492
01-28 19:13:50.787 32751   367 E AndroidRuntime: workLoopSync@1:112350
01-28 19:13:50.787 32751   367 E AndroidRuntime: renderRootSync@1:112234
01-28 19:13:50.787 32751   367 E AndroidRuntime: performSyncWorkOnRoot@1:109609
01-28 19:13:50.787 32751   367 E AndroidRuntime: flushSyncCallbacks@1:77235
01-28 19:13:50.787 32751   367 E AndroidRuntime: scheduleUpdateOnFiber@1:107268
01-28 19:13:50.787 32751   367 E AndroidRuntime: updateContainer@1:117581
01-28 19:13:50.787 32751   367 E AndroidRuntime: anonymous@1:127243
01-28 19:13:50.787 32751   367 E AndroidRuntime: renderApplication@1:446634
01-28 19:13:50.787 32751   367 E AndroidRuntime: run@1:443468
01-28 19:13:50.787 32751   367 E AndroidRuntime: runApplication@1:444004
01-28 19:13:50.787 32751   367 E AndroidRuntime: __callFunction@1:53719
01-28 19:13:50.787 32751   367 E AndroidRuntime: anonymous@1:52206
01-28 19:13:50.787 32751   367 E AndroidRuntime: __guard@1:53164
01-28 19:13:50.787 32751   367 E AndroidRuntime: callFunctionReturnFlushedQueue@1:52164
01-28 19:13:50.787 32751   367 E AndroidRuntime: 
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at java.lang.reflect.Method.invoke(Native Method)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at android.os.Handler.handleCallback(Handler.java:938)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at android.os.Handler.dispatchMessage(Handler.java:99)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at android.os.Looper.loop(Looper.java:223)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
01-28 19:13:50.787 32751   367 E AndroidRuntime:  at java.lang.Thread.run(Thread.java:923)
01-28 19:13:51.382  1369  1710 E MDD     : DownloadProgressMonitor: Can't find file group for uri: android://com.google.android.googlequicksearchbox/files/sharedminusonemodule/shared/SharedMinusOneData.pb.tmp
01-28 19:13:51.403  1369 32439 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:51.908  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:52.416  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:52.927  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:53.436  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:53.982  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:55.021  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:55.194   500   517 E JobScheduler.Background: App com.google.android.gms became active but still in NEVER bucket
01-28 19:13:55.223  1005  1515 E FrameEvents: updateAcquireFence: Did not find frame.
01-28 19:13:55.237   500   936 E VibratorService: Failed to issue command to vibrator HAL. Retrying.
01-28 19:13:55.239   500   936 E VibratorService: Failed to issue command to vibrator HAL. Retrying.
01-28 19:13:55.522  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:56.046  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:56.569  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:58.221   500   543 E PermissionMonitor: unknown permission type: -1for uid: 10178
01-28 19:13:58.285  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:58.799  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:59.315  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:59.776   500   517 E JobScheduler.Background: App com.google.android.gms became active but still in NEVER bucket
01-28 19:13:59.831  1369   407 E DeviceStateChecker: DeviceStateChecker cancelled
01-28 19:13:59.906  1936  1936 E CarrierServices: [2] ecr.a: Invalid signature found for com.android.contacts: E39B7BFBE0A67D78292F6CC62E06CA27A2EBF255
01-28 19:14:00.065  1936  1936 E CarrierServices: [2] ecr.a: Invalid signature found for com.android.contacts: E39B7BFBE0A67D78292F6CC62E06CA27A2EBF255

**Comment by krizzu** [comment] 2022-01-28 14:57
@aryantschics It does not say it's related to Async Storage - looks it tries to call a function which is undefined. Can't really tell what function it is, from this stack trace

**Comment by tido64** [comment] 2022-01-28 15:12
I'm going to close this issue. @AjayShivanagol opened the original issue and haven't replied in a while, so I'm going to assume that they've figured something out. As for everyone else trying to hijack this issue, please open new ones with repros and more details so we (the community) can try to help you.

**Closed by tido64** 2022-01-28 15:12 UTC
Labels: bug, platform: Android, need info
