### ISSUE TITLE
cannot find symbol variable AsyncStorage_db_size

### ISSUE THREAD

**Issue by techDPM** [react-native-async-storage/async-storage#872] opened 2022-11-13 11:07 UTC
### What happened?

tried to build a react native app - and get  exception in file :  ReactDatabaseSupplier.java 
exception :  cannot find symbol variable BuildConfig
i tried to go to the file and import. the  :  import com.facebook.react.BuildConfig; 
clean cache and rebuild again and get : 
cannot find symbol variable AsyncStorage_db_size in a same file 
location: class BuildConfig
 i go to BuildConfig file at com.facebook.react.BuildConfig ( online ) 
and saw there is not proprety of AsyncStorage_db_size..

 **what whould you recommend to do to solve this issue ?**  

### Version

1.4.2

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [ ] web

### System Information

```true
React Native Environment Info:
    System:
      OS: macOS 12.2
      CPU: (8) arm64 Apple M1
      Memory: 72.92 MB / 16.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
      Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.0/bin/yarn
      npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
      Watchman: 2022.10.24.00 - /opt/homebrew/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    IDEs:
      Android Studio: 2021.3 AI-213.7172.25.2113.9123335
      Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10
```

### Steps to Reproduce

while building my react native app in android - 
in ios its fine

**Comment by krizzu** [comment] 2022-11-14 09:29
`BuildConfig` is created during a compilation and lack of it means there was no build happening up front. You can try to clean Gradle build files (using `./gradlew clean` in your `android` directory) and run the app again (using `npx react-native run-android`).

I'm closing as the issue is not related to AsyncStorage, but to the local setup. Feel free to add more details tho, if necessary

**Closed by krizzu** 2022-11-14 09:29 UTC
Labels: bug
