### ISSUE TITLE
Error: Program type already present: com.reactnativecommunity.asyncstorage.AsyncStorageErrorUtil

### ISSUE THREAD

**Issue by jonneymendoza** [react-native-async-storage/async-storage#480] opened 2020-10-30 11:39 UTC
## Current behavior

Getting a multi-dex build error saying this:

`Error: Program type already present: com.reactnativecommunity.asyncstorage.AsyncStorageErrorUtil`

## Expected behavior

Successfully build my react native android app

## Repro steps
execute `npx react-native run-android --variant=release --verbose`

to build react native android project

## Environment

- **Async Storage version**:
Latest version

- **React-Native version**: 
` "react-native": "0.63.1",`

- **Platform tested**: 
Android

- **Logs/Error that are relevant**: 
`Error: Program type already present: com.reactnativecommunity.asyncstorage.AsyncStorageErrorUtil
`

**Comment by Krizzu** [comment] 2020-11-01 18:30
Make sure you don't manually install the package (auto-linking does it for you). Also, make sure that none of your dependency is also including Async Storage

**Comment by jordangrant** [comment] 2020-11-02 03:26
@Krizzu what if it is? I'm getting:

`Type com.reactnativecommunity.asyncstorage.AsyncStorageModule$2 is defined multiple times: /Users/jordangrant/cardy/android/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/194/com/reactnativecommunity/asyncstorage/AsyncStorageModule$2.class, /Users/jordangrant/cardy/android/app/build/intermediates/transforms/FirebasePerformancePlugin/debug/195/com/reactnativecommunity/asyncstorage/AsyncStorageModule$2.class`

Alluding to FirebasePerformance using it as a dependency. what now?

**Comment by tido64** [comment] 2020-12-18 01:26
@jordangrant I don't know if you've resolved this yet but I would suggest asking FirebasePerformance or maybe on StackOverflow if you haven't already. I'm going to close this issue as it's not a bug with AsyncStorage.

**Closed by tido64** 2020-12-18 01:26 UTC
Labels: question
