### ISSUE TITLE
'/@react-native-async-storage/async-storage/types/index.d.ts' is not a module

### ISSUE THREAD

**Issue by wwvevy** [react-native-async-storage/async-storage#471] opened 2020-10-24 08:06 UTC
## Current behavior

Install the storage component like the document said. And use it like normal, then the typescript will get the error
`'/@react-native-async-storage/async-storage/types/index.d.ts' is not a module`.

And i look for the d.ts file to find that module is still the old version. Like follow.
`declare module '@react-native-community/async-storage'`

## Expected behavior

No errors show.

## Repro steps

Install and use it like document said.

## Environment

- **Async Storage version**: 1.13.0
- **React-Native version**: 0.63.3
- **Platform tested**:  iOS

**Comment by tido64** [comment] 2020-10-24 08:14
This was addressed in #466. We will release 1.13.1 soon. Sorry for the inconvenience. cc @Krizzu

Closing as dupe of #469.

**Closed by tido64** 2020-10-24 08:14 UTC
